project:
  type: book
  output-dir: docs

book:
  title: "Remote Sensing Portfolio"
  author: "Emily Dugmore"
  date: "1/20/2026"
  chapters:
    - index.qmd
    - 1_RS_intro.qmd
    - 3_Enhancements.qmd
    - 4_policy.qmd
    - 5_GEE.qmd
    - 6_classification_1.qmd
    - 7_Classification_2.qmd
    - 8_Temperature.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt

editor: visual

